apiVersion: apps/v1
kind: Deployment
metadata:
  name: soap-api
  namespace: jclo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soap-api
  template:
    metadata:
      labels:
        app: soap-api
    spec:
      containers:
        - name: soap-api
          image: localhost:5000/trainers-api:10
          ports:
            - containerPort: 4000
          env:
            - name: MYSQL_HOST
              value: mysql-service.hga-database.svc.cluster.local
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: admin
            - name: MYSQL_DATABASE
              value: trainers
---
apiVersion: v1
kind: Service
metadata:
  name: soap-api-service
  namespace: jclo-api
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: soap-api
