apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: odm-database
type: Opaque
data:
  mongo-user: cm9vdA==    # Base64 de "root"
  mongo-password: ZXhhbXBsZQ==  # Base64 de "example"
  mysql-user: cm9vdA==    # Base64 de "root"
  mysql-password: YWRtaW4=  # Base64 de "admin"
