version: '3.8'

services:
  soap-api:
    build:
      context: .
    ports:
      - "4000:4000" # Puerto de la API
    restart: always
    environment:
      FLASK_ENV: development # Modo desarrollo (opcional)
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: trainers
    depends_on:
      - mysqldb
    networks:
      - soap-network

  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: trainers
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql # Persistencia de datos
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Archivo de inicialización
    networks:
      - soap-network

volumes:
  mysql-data:

networks:
  soap-network:
    driver: bridge
